# Databricks notebook source
# MAGIC %md
# MAGIC # 00: Setup & Configuration
6# MAGIC 
# MAGIC This notebook sets up the directory structures, paths, schemas, and helper functions for our Real-Time IoT Telemetry Pipeline.
# MAGIC Run this notebook at the beginning of your session or `%run ./00_Setup_Config` inside other notebooks.
# MAGIC 
# MAGIC **School Kid Analogy:** 
# MAGIC > Think of this notebook as preparing your workspace. Before you start coloring or building legos, you need to make sure you have your boxes ready and know where each piece will go!

# COMMAND ----------

# Create widgets for configuration (optional, defaults are provided)
dbutils.widgets.text("base_dir", "/tmp/realtime_iot_project", "Base DBFS Directory")

# COMMAND ----------

# Get configuration paths
base_dir = dbutils.widgets.get("base_dir").rstrip("/")

# Define standard paths in DBFS (Databricks File System)
landing_zone_path = f"{base_dir}/landing_zone"
schema_path = f"{base_dir}/_schemas"

# Medallion layers paths
bronze_path = f"{base_dir}/bronze"
bronze_checkpoint = f"{base_dir}/_checkpoints/bronze"

silver_path = f"{base_dir}/silver"
silver_checkpoint = f"{base_dir}/_checkpoints/silver"

gold_path = f"{base_dir}/gold"
gold_checkpoint = f"{base_dir}/_checkpoints/gold"

# Print configuration
print("=== PIPELINE DIRECTORY CONFIGURATION ===")
print(f"Landing Zone:      {landing_zone_path}")
print(f"Schema Store:      {schema_path}")
print(f"Bronze Delta:      {bronze_path} (Checkpoint: {bronze_checkpoint})")
print(f"Silver Delta:      {silver_path} (Checkpoint: {silver_checkpoint})")
print(f"Gold Delta:        {gold_path} (Checkpoint: {gold_checkpoint})")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Define Raw Schema
# MAGIC Defining a schema ensures data quality and helps Spark parse raw text/JSON fields safely.

# COMMAND ----------

from pyspark.sql.types import StructType, StructField, StringType, DoubleType

# Schema of the raw JSON records generated by our IoT sensors
iot_schema = StructType([
    StructField("device_id", StringType(), True),
    StructField("timestamp", StringType(), True),
    StructField("temperature", DoubleType(), True),
    StructField("humidity", DoubleType(), True),
    StructField("status", StringType(), True)
])

# COMMAND ----------

# MAGIC %md
# MAGIC ### Reset Pipeline Helper
# MAGIC Run this cell only if you want to wipe out all existing streaming data and start from scratch!
# MAGIC 
# MAGIC **Client/PM Pitch:** 
# MAGIC > Having a reset mechanism is critical for test environments. It allows automated CI/CD pipelines to run test suites under clean conditions without carrying over legacy state.

# COMMAND ----------

def reset_pipeline():
    """Wipes out all project directories to start fresh."""
    print(f"Cleaning up directories under: {base_dir}...")
    try:
        dbutils.fs.rm(base_dir, recurse=True)
        print("Reset complete! Directories cleared successfully.")
    except Exception as e:
        print(f"Error during cleanup (perhaps directories don't exist yet): {e}")

# If you want to reset, uncomment the line below and run:
# reset_pipeline()

# COMMAND ----------

# MAGIC %md
# MAGIC ### DBFS IoT Data Generator Cell
# MAGIC Run this cell to simulate streaming data **directly inside Databricks** without running a local script.
# MAGIC This will generate 10 JSON files in the landing zone with a 3-second delay.

# COMMAND ----------

import time
import random
import json

def generate_dbfs_mock_data(num_files=10, delay_seconds=3):
    """Generates mock JSON telemetry files directly in DBFS."""
    devices = ["sensor-north-01", "sensor-east-02", "sensor-south-03", "sensor-west-04"]
    
    print(f"Starting simulated data generation to {landing_zone_path}...")
    dbutils.fs.mkdirs(landing_zone_path)
    
    for i in range(1, num_files + 1):
        batch = []
        for _ in range(5):
            device_id = random.choice(devices)
            # 5% chance of high temp warning
            is_anomaly = random.random() < 0.05
            temperature = round(random.uniform(80.0, 95.0), 2) if is_anomaly else round(random.uniform(18.0, 32.0), 2)
            status = "WARNING" if is_anomaly else "OK"
            
            # 3% chance of null humidity
            humidity = None if random.random() < 0.03 else round(random.uniform(35.0, 65.0), 2)
            
            from datetime import datetime
            batch.append({
                "device_id": device_id,
                "timestamp": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z",
                "temperature": temperature,
                "humidity": humidity,
                "status": status
            })
            
        # Save to DBFS
        file_name = f"{landing_zone_path}/telemetry_dbfs_{int(time.time())}_{i}.json"
        dbutils.fs.put(file_name, json.dumps(batch, indent=2), overwrite=True)
        print(f"Created file: {file_name}")
        time.sleep(delay_seconds)
        
    print("Simulated data generation complete!")
